spring.application.name=api-gateway
server.port=9090

# ==========================================
# User Service routes
# ==========================================
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

# ==========================================
# Restaurant Service routes
# ==========================================
spring.cloud.gateway.server.webflux.routes[1].id=restaurant-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/restaurants/**

# ==========================================
# Order Service routes
# ==========================================
spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**

# ==========================================
# Payment Service routes
# ==========================================
spring.cloud.gateway.server.webflux.routes[3].id=payment-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/payments/**

# ==========================================
# Notification Service routes
# ==========================================
spring.cloud.gateway.server.webflux.routes[4].id=notification-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/notifications/**

# JWT
jwt.secret=8f3a2b9c1d4e7f0a5b6c3d8e2f1a4b7c9d0e3f6a1b4c7d0e3f6a9b2c5d8e1f4