spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=Pass@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.indent-output=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=8f3a2b9c1d4e7f0a5b6c3d8e2f1a4b7c9d0e3f6a1b4c7d0e3f6a9b2c5d8e1f4
jwt.expiration=3600000